services:
    # Mysql database container
    db:
        image: mysql
        container_name: ecom_db_symfony
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - ecom

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: ecom_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - ecom

    # Symfony apache project container
    www:
        build: docker/php
        container_name: ecom_symfony
        ports:
          - "8741:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - ecom
    
    # Mailpit container for email testing
    mailpit:
        image: axllent/mailpit
        container_name: ecom_mailpit
        restart: always
        ports:
            - "1025:1025"  # SMTP server
            - "8025:8025"  # Web UI
        networks:
            - ecom

    redis:
        image: redis
        restart: always
        ports:
            - "6379:6379"
        networks:
            - ecom

networks:
    ecom:

volumes:
    db-data: